language: objective-c
compiler: clang
os:
    - osx

env:
    matrix:
        - BUILD_CONFIG=release
        - BUILD_CONFIG=debug

script:
    - ./build.sh $BUILD_CONFIG
    - src/pal/tests/palsuite/runpaltests.sh $TRAVIS_BUILD_DIR/binaries/intermediates/mac.x64.debug $TRAVIS_BUILD_DIR/binaries/paltestout
